version: '2'


services:
    web_round_robin:
        image: ricardo-olarte/log_round_robin
        container_name: roundrobbinserver
        ports:
            - "34000:24000"
    web_log_service1:
        image: ricardo-olarte/log_service
        container_name: log_service1
        ports:
            - "35000:15000"
    web_log_service2:
        image: ricardo-olarte/log_service
        container_name: log_service2
        ports:
            - "35001:15000"
    web_log_service3:
        image: ricardo-olarte/log_service
        container_name: log_service3
        ports:
            - "35002:15000"
    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: